### ISSUE TITLE
FE Updates: Group template input based on 'tab'/'group' (This will be a good item to review with Antoine)

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#100]
Config slide out, adding tabs based on ....  there is a default behavior, if a group is not assigned it should fall under (see Daren to finish this sentence).  Store needs to finish before this item can be worked.

As option tree comes in, that the option is listed in the correct group.

**Comment by JayHuLBL** [comment]
Close as it is completed.
