### ISSUE TITLE
Set Up Domain:  LBL.GOV - http://lbl.gov/

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#110]
Per Paul (4/7/22) "I did touch base with Michael about domains and I think that this will start at [LBL.GOV](http://lbl.gov/)"

9/22/22:   Michael Wetter:  Plan to host the software on a LBL domain, such as [buildings.lbl.gov/ctrl-flow](http://buildings.lbl.gov/ctrl-flow) (or similar).

**Comment by JayHuLBL** [comment]
Close as it is completed.
