### ISSUE TITLE
Re-order how options are rendered. Ensure Options are grouped correctly.

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#138]
Currently all options get put together in one big flat list. On selection of a component, the related options from that component should be displayed in a group below the option.

For example, say you have the following options:

```
OptionA = {
    childOptions = ['OptionC', 'OptionD']
};
OptionB = {
    childOptions = []
};
OptionC = {
    childOptions = ['OptionE', 'OptionF']
}
OptionD = {
    childOptions = ['OptionG', 'OptionH']
}
OptionE = {
    childOptions = ['OptionI', 'OptionJ']
}
...
OptionI = {
   childOptions = ['OptionK', 'OptionL']
}
```

With this option tree, lets say that the starting options that are rendered is as follows:

```
OptionA
OptionB
```

On OptionA, the user selects 'OptionC' causing 'OptionC's option group to be rendered:

```
OptionA
| OptionE
| OptionF
OptionB
```

On 'OptionE', the user selects 'OptionI', causing 'OptionI's child options to be rendered (note nesting):

```
OptionA
| OptionE
| | OptionK
| | OptionL
| OptionF
OptionB
```

**Comment by JayHuLBL** [comment]
Close as it is completed.
