### ISSUE TITLE
Final Name and Branding

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#174]
1.  they want to use the LBNL branding - here is the link to the details about use of their logo etc.
[LBNL Logo and Design Standards](https://creative.lbl.gov/visual-identity/#berkeley-lab-logo). 
2.  Implement final name - ctrl-flow. "The official name that DOE settled on is ctrl-flow (rather than ControlFlow), please use ctrl-flow in the naming."
- LBL contact Karyn (khouston@lbl.gov) manages the communications office of LBL's Energy Technologies Area and can help ensure we follow the LBL guidelines.  
- Please also see https://creative.lbl.gov/visual-identity/to make sure all the LBL branding and web regulations are applied correctly. 

Use the logo we are using on the Splash page

**Comment by AntoineGautier** [comment]
Closed as completed.
