### ISSUE TITLE
Splash Page in Production

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#203]
- For the “splash page” the LBNL branding (and logo) should be included.  This page will also describe the tool as the “crtl-flow High Performance Controls Design Tool”.  

- Use the LBNL branding - here is the link to the details about use of their logo etc. [LBNL Logo and Design Standards](https://creative.lbl.gov/visual-identity/#berkeley-lab-logo).

- Implement final name - ctrl-flow. "The official name that DOE settled on is ctrl-flow (rather than ControlFlow), please use ctrl-flow in the naming."

- See https://creative.lbl.gov/visual-identity/ make sure all the LBL branding and web regulations are applied correctly.

- LBL contacts ([Kiran Julin](mailto:kjulin@lbl.gov)) and [Cristen Farley](mailto:CFarley@lbl.gov)  can help ensure we follow the LBL guidelines (Kiran) and connect with IT for the URL (Kiran).  Please include both on any communications.  We should have her sign off on the "Splash Page" before publishing in Production.

**Comment by AntoineGautier** [comment]
Closed as completed.
