### ISSUE TITLE
License and Copywrite Info

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#222]
Per 11/11 meeting with LBNL Design Team, 

- Footer - Cristen to send the html code, websites usually include this footer, Cristen acknowledged that this is more of a tool rather than website so this point can be negotiated if needed.

- If onboarding screens are popups, that is ok, but if they are actual screens they’d like the LBNL logo as the other pages have
- There is discussion between Paul and Michael if this information can go on the About Page.  If that is preferred, just let Paul know that it would help focus max time on bugs if we can include this on the Above page rather than a footer.
- Michael said the license and copyright would be something like this...  [https://simulationresearch.lbl.gov/modelica/license.html](url) and that they hoped to have it to us by the end of the year.  I think you can ask Jianjun about this.

**Comment by AntoineGautier** [comment]
Closed as completed: license and copyright information included in `About`.
