### ISSUE TITLE
Bundle all project selections to pass to the backend

### ISSUE THREAD

**Issue by akapoor66** [lbl-srg/ctrl-flow-dev#239]
This current includes New Project selections. 

-  Energy Standards
-  Ventilation Standards
-  Climate Zone
-  Units

This will also bundle all the config selections and evaluated values for a project.

-  This will remove all evaluated values that are null.
-  This will determine the proper way to pass these values to the backend

**Comment by AntoineGautier** [comment]
Closed as completed.
