### ISSUE TITLE
add Support page

### ISSUE THREAD

**Issue by Flintonian** [lbl-srg/ctrl-flow-dev#250]
Add Contact page

From designs, replace person icon with hamburger menu
Here is the [link to the text](https://docs.google.com/document/d/1tEerX91a24FN2UHeceMDb8vU5ZXd5IQN/edit#heading=h.3qrur75d92iz): 

This will be a dual approach, encouraging users to go to github discussion, and an alternative email address.

**Comment by AntoineGautier** [comment]
Closed as completed
