### ISSUE TITLE
Include redeclare modifier types in template.json

### ISSUE THREAD

**Issue by darenkeck-dev** [lbl-srg/ctrl-flow-dev#253]
Replaceable parameters can have downstream types associated in two ways:
- a 'choices' annotation
- a modifier in another class using the replaceable parameter.

Currently the parser only finds replaceable types using the 'choices' annotation. We must also find and include types that are specified in `redeclare` modifiers.

This issue is the reason parameters from `Buildings.Templates.ZoneEquipment.Components.Controls.Interfaces.G36VAVBox` (like `have_winSen`) are currently not found.

**Comment by AntoineGautier** [comment]
Closed as addressed by https://github.com/lbl-srg/ctrl-flow-dev/pull/254
