### ISSUE TITLE
Final keyword disregarded

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/ctrl-flow-dev#360]
Using commit [30fd0f3d1f](https://github.com/lbl-srg/modelica-buildings/tree/30fd0f3d1f004812b9b468b547d27d120db2bb14) of MBL, the final keyword in the following bindings is disregarded.
```mo
partial model PartialOutdoorSectionDedicatedDampers
  "Base class for modeling separate dampers for ventilation and economizer"
  extends 
    Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSection(
    final typDamOut=damOut.typ,
    final typDamOutMin=damOutMin.typ);
```
When running the app, we get the following input fields for the OA dampers, that should be disabled due to the final keyword.

<img width="358" alt="Capture d’écran 2023-09-28 à 17 07 32" src="https://github.com/lbl-srg/ctrl-flow-dev/assets/10965994/9dbf0c6c-018d-459b-a7e6-9c3404377e69">

This is surprising because this pattern is used elsewhere. For example, the type of an equipment is declared in the interface class, e.g.
```mo
partial model PartialOutdoorSection "Interface class for outdoor air section"
  parameter Buildings.Controls.OBC.ASHRAE.G36.Types.OutdoorAirSection typ
    "Outdoor air section type"
    annotation (Evaluate=true, Dialog(group="Configuration"));
```
and assigned with the final keyword in the derived class, e.g.
```mo
model DedicatedDampersAirflow
  "Separate dampers for ventilation and economizer, with airflow measurement station"
  extends Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers(
    final typ=Buildings.Controls.OBC.ASHRAE.G36.Types.OutdoorAirSection.DedicatedDampersAirflow);
```
And in this case, the app does not generate an input field for the equipment type, which is as expected.

A propable cause is that in the case of `typDamOut*`, the final assignment is made in an intermediary child class.

#### Workaround

Use `__ctrlFlow(enable=false)` annotation.
Or make final assignments for `typDamOut` and `typDamOutMin` within the interface class if possible.

**Comment by AntoineGautier** [comment]
Another occurrence of this issue appears with commit 6036d14d2d3a12376dab886a62a40d3f475f68ab of MBL and the following declaration within  `Buildings.Templates.AirHandlersFans.VAVMultiZone`.

```mo
  inner replaceable Buildings.Templates.AirHandlersFans.Components.OutdoorReliefReturnSection.MixedAirWithDamper
    secOutRel(
    redeclare final package MediumAir = MediumAir,
    final typCtlFanRet=ctl.typCtlFanRet,
    final typCtlEco=ctl.typCtlEco,
```

The input fields for `typCtlFanRet` and `typCtlEco` are enabled in the configuration dialog despite the `final` keyword. 
Here, adding a constraining clause with the class that contains the original declarations of `typCtlFanRet` and `typCtlEco`  solves the issue, i.e.,:

```mo
  inner replaceable Buildings.Templates.AirHandlersFans.Components.OutdoorReliefReturnSection.MixedAirWithDamper
    secOutRel constrainedby Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorReliefReturnSection(
    redeclare final package MediumAir = MediumAir,
    final typCtlFanRet=ctl.typCtlFanRet,
    final typCtlEco=ctl.typCtlEco,
```

**Comment by JayHuLBL** [comment]
@AntoineGautier when running the app in staging.ctrl-flow.lbl.gov, I cannot see the entry for the outdoor air section. See below the screenshot in the ctrl-flow.lbl.gov:
<img width="932" alt="Screenshot 2023-10-24 at 12 09 26 PM" src="https://github.com/lbl-srg/ctrl-flow-dev/assets/23491921/b4f1f3d0-fd9c-4fe4-ac16-1be6e3a95d19">
How can I see the screenshot as you are showing here?

**Comment by AntoineGautier** [comment]
To see the screenshot from above with the incorrect entries for the OA section, you have to locally rebuild the server app with the referenced MBL commit [30fd0f3d1f](https://github.com/lbl-srg/modelica-buildings/tree/30fd0f3d1f004812b9b468b547d27d120db2bb14).
In more recent MBL commits (such as the one used on the staging branch), a workaround was implemented where final assignments for `typDamOut` and `typDamOutMin` are made within the interface class (as opposed to the derived class as above). See the diff at https://github.com/lbl-srg/modelica-buildings/compare/30fd0f3d1f004812b9b468b547d27d120db2bb14...master#diff-cf424f8df0b9ff39c6a6b4986c14a10c865ee3b5ae1fa3e3956e630aaa0bbb34R12-R27.

What is currently visible on the staging branch is the other occurrence of this issue, described at https://github.com/lbl-srg/ctrl-flow-dev/issues/360#issuecomment-1772326895.
In this case, the workaround proposed in https://github.com/lbl-srg/ctrl-flow-dev/pull/369 uses `__ctrlFlow(enable=false)` annotation.

Note that the current issue shall remain open as these two workarounds do not solve the original problem, which is that ctrl-flow disregards some final assignments for some specific constructs.

**Comment by AntoineGautier** [comment]
The server file `templates.json` has the correct data for the interface class:
```json
    {
      "modelicaPath": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "type": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "name": "Base class for modeling separate dampers for ventilation and economizer",
      "value": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "visible": false,
      "modifiers": {
        "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSection.typDamOut": {
          "expression": {
            "operator": "none",
            "operands": [
              "damOut.typ"
            ]
          },
          "final": true,
          "redeclare": false
        },
```

The FE context also has the correct data for the interface class:
```json
    "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers": {
      "modelicaPath": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "type": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "name": "Base class for modeling separate dampers for ventilation and economizer",
      "value": "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers",
      "visible": false,
      "modifiers": {
        "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSection.typDamOut": {
          "expression": {
            "operator": "none",
            "operands": [
              "damOut.typ"
            ]
          },
          "final": true,
```

The issue is that the FE context maps the option for `typDamOut` to the top-level parent instead of the immediate parent:
```json
                {
                  "modelicaPath": "Buildings.Templates.AirHandlersFans.Components.OutdoorSection.DedicatedDampersAirflow",
                  "options": [
                    "Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSection.typDamOut",
```
Instead of `"Buildings.Templates.AirHandlersFans.Components.Interfaces.PartialOutdoorSectionDedicatedDampers.typDamOut"`.
