### ISSUE TITLE
Avoid vulnerabilities and upgrade node version

### ISSUE THREAD

**Issue by JayHuLBL** [lbl-srg/ctrl-flow-dev#362]
run `npm I` from `client` folder give following:
```
10 vulnerabilities (4 moderate, 6 high)
```

Also for the workflow setup in `.github/workflows`, node version is set to be `16.x`. It causes the error when deploying:
<img width="1176" alt="Screenshot 2023-10-06 at 11 08 27 AM" src="https://github.com/lbl-srg/ctrl-flow-dev/assets/23491921/5c89415c-e9df-46e1-a179-6aebc649a8d6">

**Comment by AntoineGautier** [comment]
Closed as completed: `node-version: [18.x]`
